all: jeffrey-hanson-cv.pdf

jeffrey-hanson-cv.pdf: jeffrey-hanson-cv.tex preamble.tex
	pdflatex jeffrey-hanson-cv.tex
	pdflatex jeffrey-hanson-cv.tex
	pdflatex jeffrey-hanson-cv.tex

clean:
	rm -f jeffrey-hanson-cv.pdf
	rm -f jeffrey-hanson-cv.aux
	rm -f jeffrey-hanson-cv.out
	rm -f jeffrey-hanson-cv.log
